image: roadiz/php83-runner
stages:
  - test

variables:
  # Timezone will be used both for system and php date.timezone php.ini value
  TIMEZONE: "Europe/Paris"
  COMPOSER_ALLOW_SUPERUSER: 1
# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
    - vendor/

test:
  stage: test
  script:
    - composer install --dev --no-scripts --no-suggest
    - vendor/bin/php-cs-fixer check --ansi -vvv
    - vendor/bin/phpstan analyse -c phpstan.neon
