services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $cachePath: '%rz_intervention_request.cache_path%'
            $subscribers: '%rz_intervention_request.subscribers%'

    RZ\InterventionRequestBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    RZ\InterventionRequestBundle\Command\CacheCommand:
        arguments:
            - '%rz_intervention_request.cache_path%'
        tags:
            - { name: 'console.command', command: 'cache:clear-images' }

    RZ\InterventionRequestBundle\InterventionRequest\InterventionRequest:
        arguments:
            - AM\InterventionRequest\Configuration
            - '%rz_intervention_request.subscribers%'

    AM\InterventionRequest\InterventionRequest:
        alias: RZ\InterventionRequestBundle\InterventionRequest\InterventionRequest

    RZ\InterventionRequestBundle\InterventionRequest\Configuration:
        arguments:
           - '%rz_intervention_request.files_path%'
           - '%rz_intervention_request.driver%'
           - '%rz_intervention_request.default_quality%'
           - '%rz_intervention_request.pngquant_path%'
           - '%rz_intervention_request.jpegoptim_path%'
           - '%rz_intervention_request.cache_path%'
           - '%rz_intervention_request.use_passthrough_cache%'

    AM\InterventionRequest\Configuration:
        alias: RZ\InterventionRequestBundle\InterventionRequest\Configuration
