parameters:
    env(IR_DEFAULT_QUALITY): '90'
    env(IR_MAX_PIXEL_SIZE): '2500'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Intervention\Image\ImageManager:
        arguments:
            - '%rz_intervention_request.driver%'

    RZ\InterventionRequestBundle\Command\CacheCommand:
        arguments:
            - '%rz_intervention_request.cache_path%'
        tags:
            - { name: 'console.command', command: 'cache:clear-images' }

    RZ\InterventionRequestBundle\Controller\DefaultController:
        tags: ['controller.service_arguments']
        arguments:
            - '@RZ\InterventionRequestBundle\InterventionRequest\InterventionRequest'
            - '%rz_intervention_request.cache_path%'

    RZ\InterventionRequestBundle\InterventionRequest\InterventionRequest:
        arguments:
            - '@RZ\InterventionRequestBundle\InterventionRequest\Configuration'
            - '@AM\InterventionRequest\FileResolverInterface'
            - '%rz_intervention_request.subscribers%'
            - '@logger'

    AM\InterventionRequest\InterventionRequest:
        alias: RZ\InterventionRequestBundle\InterventionRequest\InterventionRequest

    RZ\InterventionRequestBundle\InterventionRequest\Configuration:
        arguments:
           - '%rz_intervention_request.files_path%'
           - '%rz_intervention_request.driver%'
           - '%rz_intervention_request.default_quality%'
           - '%rz_intervention_request.pngquant_path%'
           - '%rz_intervention_request.jpegoptim_path%'
           - '%rz_intervention_request.cache_path%'
           - '%rz_intervention_request.use_passthrough_cache%'

    AM\InterventionRequest\Configuration:
        alias: RZ\InterventionRequestBundle\InterventionRequest\Configuration
